​​​​spring:
​​  datasource:
​​    url: jdbc:h2:./h2db/todoapp
​​    username: sa
​​    password:
​​    driver-class-name: org.h2.Driver
​​  jpa:
​​    hibernate:
​​      ddl-auto: update
​​    show-sql: false